server:
  port: 7011
spring:
  application:
    name: java_endpoint_a
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level:
    root: INFO
    org:
      springframework.web: DEBUG
